nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
mongo:
    image: mongo
    ports:
        - "27017"
    volumes:
        - /data/db:/data/db
cadvisor:
  container_name: cAdvisor
  build: ./cAdvisor
  ports:
    - "7788:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
influxdb:
  container_name: influxdb
  image: tutum/influxdb:0.12
  ports:
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    PRE_CREATE_DB: wadus
grafana:
  container_name: grafana
  image: grafana/grafana
  links:
    - influxdb:influxdb
  ports:
    - "3000:3000"
