nginx:
    container_name: nginx
    build: ./nginx
    links:
        - node1:node1
    ports:
        - "80:80"
    volumes_from:
        - logs
node1:
    container_name: node1
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
    volumes_from:
      - logs
    environment:
      - LOG_FILE=/var/log/mointor.log/node.log
redis:
    container_name: redis
    image: redis
    ports:
        - "6379"
mongoData:
  container_name: data-container-mongo
  image: busybox:latest
  volumes:
    - /data/db:/data/db
  entrypoint: /bin/sh

mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017"
    volumes_from:
        - mongoData

logs:
  container_name: data-container-logs
  image: busybox:latest
  volumes:
    - "/var/log/mointor.log:/var/log/mointor.log:rw"
    - "/var/log/nginx:/var/log/nginx:rw"
  entrypoint: /bin/sh

cadvisor:
  container_name: cAdvisor
  build: ./cAdvisor
  ports:
    - "7788:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"

logstashData:
  container_name: data-container-logstash
  image: busybox:latest
  volumes:
    - /logstash/data:/logstash
  entrypoint: /bin/sh
logstash:
  container_name: logstash
  build: ./logstash
  volumes_from:
      - logs
      - logstashData

prometheusData:
  container_name: data-container-prometheus
  image: busybox:latest
  volumes:
    - "/prometheus-data:/prometheus-data:rw"
  entrypoint: /bin/sh
prometheus:
  container_name: prometheus
  build: ./my-prometheus
  ports:
    - "9090:9090"
  volumes_from:
    - prometheusData

grafana:
  container_name: grafana
  image: grafana/grafana
  links:
    - prometheus:prometheus
  ports:
    - "3000:3000"
