nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
mongo:
    image: mongo
    ports:
        - "27017"
    volumes:
        - /data/db:/data/db

cadvisor:
  container_name: cAdvisor
  build: ./cAdvisor
  ports:
    - "7788:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
logstash:
  image: logstash:latest
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/winston-prometheus.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/data:/logstash
prometheus:
  container_name: prometheus
  build: ./my-prometheus
  ports:
    - "9090:9090"
  volumes:
    - /prometheus-data
grafana:
  container_name: grafana
  image: grafana/grafana
  links:
    - prometheus:prometheus
  ports:
    - "3000:3000"
