nginx:
    container_name: nginx
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    container_name: node1
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
    volumes_from:
      - logs
    environment:
      - LOG_FILE=/var/log/mointor.log/node.log
node2:
    container_name: node2
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
    volumes_from:
        - logs
    environment:
        - LOG_FILE=/var/log/mointor.log/node.log
node3:
    container_name: node3
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080"
    volumes_from:
        - logs
    environment:
        - LOG_FILE=/var/log/mointor.log/node.log
redis:
    container_name: redis
    image: redis
    ports:
        - "6379"

logs:
  container_name: data-container-logs
  image: busybox:latest
  volumes:
    - "/var/log/mointor.log:/var/log/mointor.log:rw"
  entrypoint: /bin/sh

mongoData:
  container_name: data-container-mongo
  image: busybox:latest
  volumes:
    - /data/db:/data/db
  entrypoint: /bin/sh

mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017"
    volumes_from:
        - mongoData

cadvisor:
  container_name: cAdvisor
  build: ./cAdvisor
  ports:
    - "7788:8080"
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"

logstash:
  image: logstash:latest
  container_name: logstash
  command: logstash -f /etc/logstash/conf.d/winston-prometheus.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/data:/logstash

prometheusData:
  container_name: data-container-prometheus
  image: busybox:latest
  volumes:
    - "/prometheus-data:/prometheus-data:rw"
  entrypoint: /bin/sh
prometheus:
  container_name: prometheus
  build: ./my-prometheus
  ports:
    - "9090:9090"
  volumes_from:
    - prometheusData

grafana:
  container_name: grafana
  image: grafana/grafana
  links:
    - prometheus:prometheus
  ports:
    - "3000:3000"
